### ISSUE TITLE
after running app it is showing blank screen

### ISSUE THREAD

**Issue by NikunjSakhare2519** [satendra03/trip-planner-by-satendra#1]
i have followed all steps carefully still it is not running

**Comment by satendra03** [comment]
Thanks for reaching out and for raising this issue.

 If you’re encountering a blank screen, it most likely means that the **_API keys haven’t been set up correctly_**. Please double-check that the keys for Google OAuth and other APIs are properly configured in the` .env` file as per the README instructions.
