### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ThomBuyck** [satendra03/trip-planner-by-satendra#2]
Hi @satendra03, 

Really cool project you've build! I try to set it up locally but unfortunately run into some problems. The homepage works fine, when I try the plan-a-trip page I get a black screen with "Something went wrong". I believe I setup the api keys the right way, do you have an idea what might be going wrong?

Looking foreward to hearing from you and thanks in advance!

Thom

**Comment by satendra03** [comment]
Hi @ThomBuyck ,
Thank you for the appreciation! I'm really glad you like the project!

The "Something went wrong" message is rendered from constant/Error.jsx, and it generally indicates an error on the page. For the 'plan-a-trip' page, the most common issue I can think of is related to the Google Places input field.

Please make sure you've correctly set up the .env file. A common mistake developers make is not renaming the .env.sample file to .env, so double-check that this step has been done.

If everything seems fine and the issue persists, could you please share any console error messages or screenshots? That way, I can help pinpoint the exact cause of the issue.

**Comment by ThomBuyck** [comment]
Hi @satendra03 ,

Thanks for the quick reply, I indeed forgot to rename the .env file. All seems to be working now.

Thank again!
